if: branch !~ ^v\d
language: node_js
node_js: node
matrix:
  include:
  - dist: xenial
    after_success: node_modules/.bin/nyc report | npx coveralls
  - os: osx
    osx_image: xcode10.1
    script: node test/test.js
  - os: windows
    script: node test\\test.js
